<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlMap [
        <!ELEMENT sqlMap (sql*)>
        <!ELEMENT sql (#PCDATA)>
        <!ATTLIST sql id  CDATA #REQUIRED>
        ]>
<sqlMap>
    <sql id="QUERY_ID_TEST1">
        <![CDATA[select a.userCode,a.uintCode,b.projectID,
				b.name as projectName,b.projectType,b.totalPoeples
				from projectInfo b join projectOwner a  on a.projectID=b.projectID
				 [companyType | join CompanyInfo c on b.companyId=c.companyId]
				where 1=1 {projectOwner:a,projectInfo:b}
				[projectType:pt| and b.projectType=:pt]
				[:companyType,:companyName | and
				 	 c.companyType=:companyType and c.companyName like :companyName]
				 order by b.name ]]>
    </sql>

    <sql id="LIST_ALL_USER">
        <![CDATA[
            select USER_CODE as userCode, USER_PIN as userPin , IS_VALID as isValid, USER_TYPE as userType,
                LOGIN_NAME as loginName, USER_NAME as userName, ENGLISH_NAME as englishName, USER_DESC as userDesc,
                LOGIN_TIMES as loginTimes, ACTIVE_TIME as activeTime, PWD_EXPIRED_TIME as pwdExpiredTime, LOGIN_IP as loginIp,
                ADDRBOOK_ID as addrbookId, REG_EMAIL as regEmail ,  REG_CELL_PHONE as regCellPhone, USER_WORD as userWord,
                USER_TAG as userTag, USER_ORDER as userOrder, PRIMARY_UNIT as primaryUnit
            from F_USERINFO
        ]]>
    </sql>

    <sql id="UPDATE_USER_PASSWORD">
        <![CDATA[ update F_USERINFO set USERPIN = ? where USERCODE = ? ]]>
    </sql>

    <sql id="LIST_ALL_OPTINFO">
        <![CDATA[
            select OPTID as optId, PREOPTID as preOptId, OPTNAME as optName, OPTTYPE as optType,
                FORMCODE as formCode, OPTROUTE as optRoute, OPTURL as optUrl, MSGNO as msgNo,
                MSGPRM as msgPrm, ISINTOOLBAR as isInToolbar, IMGINDEX as imgIndex, TOPOPTID as topOptId,
                FLOWCODE as flowCode, PAGETYPE as pageType, ORDERIND as orderInd, ICON as icon,
                HEIGHT as height, WIDTH as width, CREATEDATE as createDate, CREATOR as creator,
                UPDATOR as updator, UPDATEDATE as updateDate
            from F_OPTINFO
        ]]>
    </sql>

    <sql id="LIST_ALL_OPTMETHOD">
        <![CDATA[
            select OPTCODE as optCode, OPTNAME as optName, OPTID as optId, OPTMETHOD as optMethod,
                OPTDESC as optDesc, ISINWORKFLOW as isInWorkflow, OPTURL as optUrl, OPTREQ as optReq,
                CREATEDATE as createDate, CREATOR as creator, UPDATOR as updator, UPDATEDATE as updateDate,
                OPTORDER as optOrder
            from F_OPTDEF
        ]]>
    </sql>

    <sql id="LIST_ALL_ROLEINFO">
        <![CDATA[
            select ROLECODE as roleCode, ROLENAME as roleName, ISVALID as isValid, ROLETYPE as roleType,
                UNITCODE as unitCode, ROLEDESC as roleDesc, CREATEDATE as createDate, CREATOR as creator,
                UPDATOR as updator, UPDATEDATE as updateDate
            from F_ROLEINFO
        ]]>
    </sql>

    <sql id="LIST_ALL_ROLEPOWER">
        <![CDATA[
            select ROLECODE as roleCode, OPTCODE as optCode, CREATEDATE as createDate, OPTSCOPECODES as optScopeCodes,
                CREATOR as creator, UPDATOR as updator, UPDATEDATE as updateDate
            from F_ROLEPOWER
        ]]>
    </sql>

    <sql id="LIST_ALL_USERROLE">
        <![CDATA[
            select USERCODE as userCode, ROLECODE as roleCode, OBTAINDATE as obtainDate, CHANGEDESC as changeDesc,
                CREATEDATE as createDate, CREATOR as creator, UPDATOR as updator, UPDATEDATE as updateDate
            from F_USERROLE
        ]]>
    </sql>

    <sql id="LIST_ALL_UNITINFO">
        <![CDATA[
            select UNITCODE as unitCode, PARENTUNIT as parentUnit, UNITTYPE as unitType, ISVALID as isValid,
                UNITNAME as unitName, ENGLISHNAME as englishName, UNITSHORTNAME as unitShortName, UNITWORD as unitWord,
                UNITTAG as unitTag, UNITDESC as unitDesc, ADDRBOOKID as addrbookId, UNITORDER as unitOrder,
                UNITGRADE as unitGrade, DEPNO as depNo, UNITPATH as unitPath, UNITMANAGER as unitManager,
                CREATEDATE as createDate, CREATOR as creator, UPDATOR as updator, UPDATEDATE as updateDate
            from F_UNITINFO
        ]]>
    </sql>

    <sql id="LIST_ALL_USERUNIT">
        <![CDATA[
            select USERUNITID as userUnitId, UNITCODE as unitCode, USERCODE as userCode, USERSTATION as userStation,
                USERRANK as userRank, RANKMEMO as rankMemo, ISPRIMARY as isPrimary, USERORDER as userOrder,
                CREATEDATE as createDate, CREATOR as creator, UPDATOR as updator, UPDATEDATE as updateDate
            from F_USERUNIT
        ]]>
    </sql>

    <sql id="LIST_ALL_DATACATALOG">
        <![CDATA[
            select CATALOGCODE as catalogCode, CATALOGNAME as catalogName, CATALOGSTYLE as catalogStyle, CATALOGTYPE as catalogType,
                CATALOGDESC as catalogDesc, FIELDDESC as fieldDesc, NEEDCACHE as needCache, OPTID as optId,
                CREATEDATE as createDate, CREATOR as creator, UPDATOR as updator, UPDATEDATE as updateDate
            from F_DATACATALOG
        ]]>
    </sql>

    <sql id="LIST_ALL_DICTIONARY">
        <![CDATA[
            select CATALOGCODE as catalogCode, DATACODE as dataCode, EXTRACODE as extraCode, EXTRACODE2 as extraCode2,
                DATATAG as dataTag, DATAVALUE as dataValue, DATASTYLE as dataStyle, DATAORDER as dataOrder,
                DATADESC as dataDesc, CREATEDATE as createDate, LASTMODIFYDATE as lastModifyDate
            from F_DATADICTIONARY
        ]]>
    </sql>
</sqlMap>